import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { store } from "./store";
import PrimeVuePlugin from "./plugins/primevue-plugin";
import { key } from "./store/store.types";
const app = createApp(App);
app.use(store, key);
app.use(router);
app.use(PrimeVuePlugin);
app.mount("#app");
